name: 🚀 Deployment on push to branch

on:
  push:
    branches: [ "branch_name" ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: server-ftp
        username: username-server-ftp
        password: password-serevr-ftp
        protocol: ftps
        port: 21
        exclude: |
          */.git
          /.git/*
          /node_modules/
          /storage/
